project:
  type: website

website:
  title: "Bulent Soykan"
  favicon: icon.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bulentsoykan
      - icon: twitter
        href: https://x.com/bulentsoykan
      - icon: linkedin
        href: https://www.linkedin.com/in/bulent-soykan/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



